name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check HTML file
      run: |
        if [ -f index.html ]; then 
          echo "index.html exists."
        else
          echo "index.html does not exist."
          exit 1
        fi
